// Generated from the FlutterFlow Dart sources by scripts/gen_data.py.
// Do not edit by hand.
export const OFFENSIVE_WORDS = [
  "420blaze",
  "69delicia",
  "aborto",
  "amador",
  "aranha",
  "ariano",
  "ariano supremo",
  "aut1st4",
  "autista de merda",
  "b o c e t 4",
  "b o c e t a",
  "b o s t a",
  "b0c3t4",
  "b0ceta",
  "b0st4",
  "b3s7a",
  "b3st@",
  "b@se@d0",
  "bagulh0",
  "bagulho doido",
  "balalao",
  "baph0m3t",
  "baphomet",
  "baseado",
  "bastardo",
  "biba",
  "biba loka",
  "bicha",
  "bichinha",
  "biscate",
  "bissexual",
  "boceta",
  "boiola",
  "boob",
  "bosta",
  "br@nc0 suprem@",
  "branco supremo",
  "braulio de borracha",
  "bumbum",
  "burro",
  "c 0 r n 0",
  "c l i t o r i s",
  "c o r n o",
  "c u z i n h a",
  "c u z ã o",
  "c0m3r",
  "c0rn0",
  "c4r4lh0",
  "c@r4lh0",
  "cabrao",
  "cacete",
  "cagar",
  "camisinha",
  "car4i0",
  "caralho",
  "cerveja",
  "ch o c h o t a",
  "ch0ch0ta",
  "ch3ir4dor",
  "cheirador",
  "cheirador de pó",
  "chochota",
  "chupar",
  "cl1t0r1s",
  "clitoris",
  "cocaína",
  "coito",
  "colhoes",
  "comedor",
  "comequieto",
  "comer",
  "cona",
  "consolo",
  "corno",
  "cr@ckud0",
  "crackudo",
  "cu",
  "d4r 0 r4b0",
  "dar o rab@0",
  "dar o rabo",
  "defici3nt3",
  "deficiente",
  "demon10 d0 s3x0",
  "demônio do sexo",
  "downzento",
  "downzinh0",
  "dum raio",
  "esporra",
  "esquizofrênico",
  "f o d a",
  "f o d a s e",
  "f o d e r",
  "f u c k g 0 d",
  "f u c k m e",
  "f.od.a",
  "f0d4",
  "f0d4-s3",
  "f0d4-se",
  "f0d4s3",
  "f0d@",
  "f0d@-s3",
  "f0d@dor",
  "f0d@s3",
  "f0der",
  "f1lh0 d4 put4",
  "fecal",
  "filh0 d@ pvt@",
  "filho d4 p u t 4",
  "filho da puta",
  "foda",
  "foda-se",
  "foder",
  "fuckgod",
  "fuckme",
  "fum@d0r",
  "fumador",
  "fumador de pedra",
  "g 0 z a",
  "g o s t o s a",
  "g o z a r",
  "g0rd0 fedido",
  "g0s7os0n@",
  "g0st0s0",
  "g0st0sinha",
  "g0xxt0s4",
  "g0z4",
  "g0z@r",
  "gata pelada",
  "gostosona",
  "gozar",
  "grelho",
  "h a r d c o c k",
  "h1tl3r",
  "hardcock",
  "heroína",
  "heterosexual",
  "hitler",
  "homem gay",
  "homoerótico",
  "homosexual",
  "inferno",
  "k u k l u x",
  "kkk",
  "ku klux klan",
  "l1ck me",
  "l1ckm3",
  "lick m y balls",
  "lickme",
  "lickmyballs",
  "lolita",
  "lésbica",
  "m 3 r d @",
  "m e c o m e",
  "m e r d a",
  "m3rch4",
  "m3rd@",
  "m3t3r0la",
  "m4c4c0",
  "mac0nha",
  "macaco",
  "maconheiro",
  "mama",
  "me come",
  "merda",
  "mete r 0 l a",
  "mongol0id3",
  "mongoloide",
  "n1g4",
  "n1gg4",
  "n1gg@",
  "n1gga",
  "n@z1",
  "n@zista",
  "nazista",
  "negro fedido",
  "nigg4",
  "p @ u",
  "p e n e t r a",
  "p e n i s",
  "p i n t o",
  "p o r r a",
  "p u t a",
  "p v t a",
  "p.a.u",
  "p.u.t.a",
  "p0rra",
  "p1nt0",
  "p3.nis",
  "p3n1s",
  "p3n3trador",
  "p3nis",
  "p4u",
  "p@ss@r um ch3qu3",
  "p@ssar um ch3qu3",
  "p@u",
  "paneleiro",
  "passar um cheque",
  "pau",
  "pauzinh0",
  "pauzudo",
  "pauzão",
  "peidar",
  "pinto",
  "porra",
  "pr0stitut@",
  "pr3t0 i m u n d o",
  "preto imundo",
  "put@",
  "puta",
  "puta que pariu",
  "puta que te pariu",
  "putinha",
  "pvt@",
  "pvta",
  "pênis",
  "queca",
  "r o l a",
  "r o l a z a o",
  "r0l@",
  "r3t4rd4do",
  "ret4rd",
  "retard",
  "retardado",
  "rol4o",
  "rol@ gr@nd3",
  "rola",
  "rola grande",
  "s3x u a l",
  "s3x0",
  "s3xu4l",
  "s3xy",
  "s4.k0",
  "s4c0",
  "s4c@n@g3m",
  "s4t4n",
  "s4tanz1nh0",
  "sacanagem",
  "saco",
  "satan",
  "satanzinho",
  "senta a k i",
  "senta aqui",
  "sl4v30wn3r",
  "slaveowner",
  "sniffer",
  "tarado",
  "taradão",
  "transar",
  "v 1 a d o",
  "v 4 g i n a",
  "v a i t e f o d e r",
  "v a i t o m a r n o c u",
  "v i 4 d o",
  "v i a d i n",
  "v i a d o",
  "v14d0",
  "v1ad0",
  "v4d14",
  "v4g1n4",
  "v4g1n@",
  "v@i t0m@r n0 cu",
  "v@i t3 f0d3r",
  "vadia",
  "vadinh@",
  "vai se f@d3r",
  "vai t@ m@r",
  "vai tomar no cu",
  "vai-te foder",
  "vait0m@rnocu",
  "veado",
  "vemnimim",
  "vemnimim gostosa",
  "viado",
  "viadooo",
  "vibrador",
  "wh1t3p0w3r",
  "whitepower",
  "x @ n a",
  "x a n a",
  "x o c h o t a",
  "x0ch0ta",
  "x4n4",
  "x@n@",
  "xana",
  "xaninha",
  "xochota",
  "zé povinho",
  "ânus"
];
